#! /usr/bin/python

import sys
sys.path.append("../brf/msconfig")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

MAPFILE = '../brf/msconfig/brf.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)
