#! /usr/bin/python

import sys
sys.path.append("../brrc")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

MAPFILE = '../brrc/brrc.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)
