#! /usr/bin/env python

import cgi, sys

import subprocess

data_dir = "../brrc/netcdf/"

t = "Summer_L50_dBZ_Hr%s_Freq_%s_Hz.tif-16.tif.nc"

hours = [ "00", "02", "04", "06", "08", "10", "12", "14", "16", "18", "20", "22"]
freq_groups = ["12-125", "160-1250", "1600-12500"]

params = cgi.FieldStorage()
argstring = params["args"].value
arglist = argstring.split(",")
lat = arglist[0]
lon = arglist[1]
output = []

for g in freq_groups:
	for h in hours:
		f = t % (h, g)
		p = data_dir + f
		val = subprocess.check_output(['gdallocationinfo', '-wgs84', '-valonly', p, lat, lon])
		val = val.split("\n")
		val.remove("")
		output.append("%s,%s" % (f.rstrip(".tif-16.tif.nc"), val[0]))

print 'Content-type: application/json\n'
print output

