#! /usr/bin/python

import sys
sys.path.append("../landat/msconfig")
import CGIUtils
sys.path.append("../var")
from Config import *

MAPFILE = '../landat/msconfig/landat-dev.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE_TEST)
