#! /usr/bin/python

import sys
sys.path.append("../samab/msconfig")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

MAPFILE = '../samab/msconfig/samab-natural.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)
